# Generated by Django 4.2.4 on 2023-08-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_session_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_year',
            old_name='session_ent',
            new_name='session_end',
        ),
    ]
